version: "3"
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydb
    networks:
      - my_network
  mongodb:
    image: mongo:latest
    container_name: mongo_local
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - my_network

volumes:
  mongodb_data:
    driver: local

networks:
  my_network:
    driver: bridge
