version: "3.8"
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    environment:
      - DB_URL="mongodb://mongodb:${PORT}/${DB_NAME}"
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${ROOT_USERNAME}"
      - MONGO_INITDB_ROOT_PASSWORD="${ROOT_PASSWORD}"
    networks:
      - my_network

volumes:
  mongodb_data:
    driver: local

networks:
  my_network:
    driver: bridge
